namespaceOverride: "observability"

grafana:
  namespaceOverride: "observability"
  enabled: true
  additionalDataSources: 
  - name: loki
    access: proxy
    editable: true
    orgId: 1
    type: loki
    url: http://loki.observability.svc:3100
    version: 1
    jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: jaeger
              matcherRegex: "traceId:([A-Za-z0-9]+)"
              name: TraceID
              url: '$${__value.raw}'
  - name: jaeger
    access: proxy
    editable: true
    orgId: 1
    type: jaeger
    url: http://simplest-query.observability.svc:16686
    version: 1
    jsonData:
        nodeGraph: 
          enabled: true
        tracesToLogs:
          datasourceUid: 'loki'
          tags: ['app']
          spanStartTimeShift: '0s'
          spanEndTimeShift: '4h'
          filterByTraceID: true
          filterBySpanID: true
  

kube-state-metrics:
  namespaceOverride: "observability"
kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
prometheus-node-exporter:
  namespaceOverride: "observability"

prometheus:
  enabled: true
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: mongodb
        scrape_interval: 15s
        scheme: http
        metrics_path: /metrics
        static_configs:
          - targets: ['mongo-exporter-prometheus-mongodb-exporter.mongodb.svc.cluster.local:9216']
      - job_name: api-blogs
        scrape_interval: 15s
        scheme: http
        metrics_path: /metrics
        static_configs:
          - targets: ['api-blogs-svc.app.svc.cluster.local:3005']