apiVersion: v1
kind: Service
metadata:
  name: api-blogs-svc
  namespace: app
spec:
  ports:
  - name: app
    port: 3005
    protocol: TCP
    targetPort: 3000
  selector:
    app: api-blogs
  type: ClusterIP
